### ISSUE TITLE
Pods folder missing

### ISSUE THREAD

**Issue by wellkunnected** [SuperChloe/Continuous#1]
Hi,

Can you include the pods folder for the app? It's really a pain to have to create a pod folder for an app that should include it, if you can it would help me build the app on my iPhone 6+. Thanks for your help!

**Comment by SuperChloe** [comment]
It is fairly common practice to put the pods folder in the .gitignore, you can install all the required pods using the podfile, and in this instance there is no reason for me to have my pods folder included in my version control.
This app is available in the App Store if you just want to demo it - http://continuousapp.com

**Comment by wellkunnected** [comment]
I wasn't looking to just demo it but nevermind ill do the pods folder
myself.

On Wednesday, April 13, 2016, Chloe Horgan notifications@github.com wrote:

> It is fairly common practice to put the pods folder in the .gitignore, you
> can install all the required pods using the podfile, and in this instance
> there is no reason for me to have my pods folder included in my version
> control.
> This app is available in the App Store if you just want to demo it -
> http://continuousapp.com
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209610000

## 

Founded Well Kunnected, Inc 2010

**Comment by SuperChloe** [comment]
Ok, feel free to play around but please remember that default copyright laws apply in the absence of an explicit license - so nobody else may reproduce, distribute, or create derivative works from my work. :)

Thank you!

**Comment by wellkunnected** [comment]
Well aware but I don't see the point in open sourcing the project if that's
the case :D

On Wednesday, April 13, 2016, Chloe Horgan notifications@github.com wrote:

> Ok, feel free to play around but please remember that default copyright
> laws apply in the absence of an explicit license - so nobody else may
> reproduce, distribute, or create derivative works from my work. :)
> 
> Thank you!
> 
> > On Apr 13, 2016, at 3:27 PM, wellkunnected <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > I wasn't looking to just demo it but nevermind ill do the pods folder
> > myself.
> > 
> > On Wednesday, April 13, 2016, Chloe Horgan <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > It is fairly common practice to put the pods folder in the .gitignore,
> > > you
> > > can install all the required pods using the podfile, and in this
> > > instance
> > > there is no reason for me to have my pods folder included in my version
> > > control.
> > > This app is available in the App Store if you just want to demo it -
> > > http://continuousapp.com
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209610000>
> > 
> > ## 
> > 
> > Founded Well Kunnected, Inc 2010
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209611153>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209613807

## 

Founded Well Kunnected, Inc 2010

**Comment by SuperChloe** [comment]
Because GitHub is frequently used to supplement a resume, and is an easy way to show employers our code.

**Comment by wellkunnected** [comment]
Understood

On Wednesday, April 13, 2016, Chloe Horgan notifications@github.com wrote:

> Because GitHub is frequently used to supplement a resume, and is an easy
> way to show employers our code.
> 
> > On Apr 13, 2016, at 3:34 PM, wellkunnected <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > Well aware but I don't see the point in open sourcing the project if
> > that's
> > the case :D
> > 
> > On Wednesday, April 13, 2016, Chloe Horgan <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > Ok, feel free to play around but please remember that default copyright
> > > laws apply in the absence of an explicit license - so nobody else may
> > > reproduce, distribute, or create derivative works from my work. :)
> > > 
> > > Thank you!
> > > 
> > > > On Apr 13, 2016, at 3:27 PM, wellkunnected <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > 
> > > > I wasn't looking to just demo it but nevermind ill do the pods folder
> > > > myself.
> > > > 
> > > > On Wednesday, April 13, 2016, Chloe Horgan <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > 
> > > > > It is fairly common practice to put the pods folder in the
> > > > > .gitignore,
> > > > > you
> > > > > can install all the required pods using the podfile, and in this
> > > > > instance
> > > > > there is no reason for me to have my pods folder included in my
> > > > > version
> > > > > control.
> > > > > 
> > > > > ## This app is available in the App Store if you just want to demo it
> > > > > 
> > > > > http://continuousapp.com
> > > > > 
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > 
> > > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209610000>
> > > 
> > > > ## 
> > > > 
> > > > Founded Well Kunnected, Inc 2010
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > > Reply to this email directly or view it on GitHub <
> > > 
> > > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209611153>
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209613807>
> > 
> > ## 
> > 
> > Founded Well Kunnected, Inc 2010
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209614025>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SuperChloe/Continuous/issues/1#issuecomment-209614601

## 

Founded Well Kunnected, Inc 2010
